# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: Github IO
url: https://cotton00.github.io/blog/
feed: /atom.xml
author_info: <a href="https://cotton00.github.io/blog/">Bin Yu</a>

myblog:
  gavatar: images/2.jpg
  gpname: litaotao
  #linkedin: http://www.linkedin.com/in/binyu
  #github: https://github.com/
  #email: mailto:***@gmail.com
  coverimgs: []
  postbgimg: []

categories: [java, books]
theme: jekyll-theme-minimal
